version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1-node
    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler

      - run:
          name: Which bundler?
          command: bundle -v

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle config set path 'vendor/bundle' || bundle config set deployment 'true'
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
