version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node
    steps:
      - checkout

      - run:
          name: Which bundler?
          command: bundle -v

      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
